FROM pegi3s/r_project:4.1.1

RUN apt-get install -y gfortran libblas-dev liblapack-dev && \
    apt install -y libxml2-dev  && \
    R -e "install.packages('XML')"  && \
    apt install -y libcurl4-openssl-dev  && \
    R -e "install.packages('RCurl')"  && \
    apt install -y libssl-dev  && \
    R -e "install.packages('httr')"  && \
    apt install -y libpng-dev  && \
    R -e "install.packages('png')"

RUN R -e "install.packages('BiocManager'); library('BiocManager'); BiocManager::install('DESeq2')"
