# R + DESeq
FROM r-base:4.1.1
RUN apt-get update && apt-get install -y procps libssl-dev libcurl4-gnutls-dev curl git libopenmpi-dev openmpi-bin openmpi-doc libxml2-dev \
    && R -e 'if (!requireNamespace("BiocManager", quietly = TRUE)){install.packages("BiocManager")}' \
    && R -e 'BiocManager::install("DESeq2")' 

ENTRYPOINT ["/usr/bin/R"]
