# base image : ubuntu
FROM ubuntu:22.04
RUN apt-get update --fix-missing \
&& apt-get install -y wget \
&& cd /usr/local/ \
&& wget https://sourceforge.net/projects/subread/files/subread-2.0.3/subread-2.0.3-Linux-x86_64.tar.gz \
&& tar -xzvf subread-2.0.3-Linux-x86_64.tar.gz \
&& cp -r subread-2.0.3-Linux-x86_64 /usr/local/bin \
&& chmod +x /usr/local/bin/subread-2.0.3-Linux-x86_64 \
&& rm subread-2.0.3-Linux-x86_64.tar.gz \
&& rm -rf subread-2.0.3-Linux-x86_64

ENTRYPOINT ["/usr/local/bin/subread"]
